### ISSUE TITLE
Set-up Instruction + HACS integration missing

### ISSUE THREAD

**Issue by al31c0** [alistair23/AutoMower-BLE#5]
Hi,

Can you provide a simple set-up instruction with HA environment?

Could be great using HACS too to install the repo.

Thank you

**Comment by Fayrewood** [comment]
Also interested to understand how to get the code into HA.

I hve various Shelly Devices which have BT proxy configured.

Just not sure how to get the code into HA as a service / integration. So any pointers gratefully received! 

Happy to support the project as well, as I've been looking to get my 305 integrated for ages $ 😎

**Comment by alistair23** [comment]
Documentation is available here: https://github.com/home-assistant/home-assistant.io/pull/30921#issuecomment-2017744301

The PR code includes details on general HA setup. The PR comment contains details on adding the component to HA before it's merged.

Feel free to file PRs against my fork for any documentation improvements.

I would rather spend time and energy getting this upstream to HA instead of maintaining a HACS integration

**Comment by alistair23** [comment]
The next HA release will include support for this
