### ISSUE TITLE
Internal Bluetooth Adapter connection does not work

### ISSUE THREAD

**Issue by sonorobby** [alistair23/AutoMower-BLE#86]
Dear Developer, thanks for this great integration.

I wanted to give the feedback and feature request as follows.

I tried several times to connect via internal ble adapter of my Raspi 3 and the connection did not work.

Then I setup the ble proxy (esphome) and everything is working fine.

Is there a reason why with the  internal ble raspi 3 is not possible to establish a connection? Cause a separate ble adapter is really bot needed.

Maybe this could be a feature that can be enabled.

**Comment by alistair23** [comment]
BLE from a Linux PC works fine, that's how the entire library was developed. If it doesn't work can you open an issue with logs, system details and describe exactly what doesn't work.

It sounds like you might have meant you used a BLE adapter with Home Assistant, considering the fix was to use ESPHome. HA doesn't recommend this: https://www.home-assistant.io/integrations/bluetooth/#before-you-begin

That's an issue with HA, that will need to be taken up there as we just use the HA BLE infrastructure.
